### ISSUE TITLE
Heptagon/Septagon

### ISSUE THREAD

**Issue by bladecoates** [knox-dawson/rm-shapes#1]
Love the project, would you be able to add a Heptagon/Septagon template? If not I understand.

**Comment by knox-dawson** [comment]
Does this fit the bill? https://github.com/knox-dawson/rm-shapes/wiki/Septagons

**Comment by bladecoates** [comment]
Definitely fits the bill. What you have is perfect and is all I needed. The right/left versions are completely up to you, probably good to save some stuff for a v2 once you get traction so you don't suffer burnout or fatigue and can focus on number of shapes vs variety of a particular shape.

Thank you!

**Comment by knox-dawson** [comment]
I'm less worried about fatigue than about putting up too much stuff that nobody really wants/needs.
Thanks for your interest and feedback.
